management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: MAGI
    version: '@project.version@'
spring:
  profiles:
    active: dev